add Gnome
SolastaMods/SolastaCommunityExpansion pull request #1009
Opened 2022-03-31 06:36 UTC by ThyWoof

2022-03-31 07:29 UTC, PhilPJL commented on SolastaCommunityExpansion/Models/RacesContext.cs
> +        private static T MemberwiseClone<T>(T base_object)
I don't think this is doing what you expect.  It's a shallow copy so you may find modifying collections in the copy modify the original.

Try this in LinqPad

```
void Main()
{
	var t = new Test { Number = 1, Items = new List<string> { "one", "two" }};

	t.Number.Dump("orig");
	string.Join(",", t.Items).Dump("orig");

// take copy
	var t2 = MemberwiseClone(t);

// modify original
	t.Number = 5;
	t.Items.Add("three");

// we see change to Items
	t2.Number.Dump("copy");
	string.Join(",", t2.Items).Dump("copy");
}

class Test
{
	public int Number {get;set;}
	public List<string> Items {get;set;}
}
// Define other methods and classes here
private static T MemberwiseClone<T>(T base_object)
{
	MethodInfo memberwiseCloneMethod = typeof(T).GetMethod("MemberwiseClone", BindingFlags.Instance | BindingFlags.NonPublic);
	return (T)memberwiseCloneMethod.Invoke(base_object, null);
}
```

2022-03-31 07:29 UTC, PhilPJL commented on SolastaCommunityExpansion/Models/RacesContext.cs
> +    public class RacesContext
public static

2022-03-31 07:32 UTC, PhilPJL commented on SolastaCommunityExpansion/Models/RacesContext.cs
> +        private static T MemberwiseClone<T>(T base_object)
See https://docs.microsoft.com/en-us/dotnet/api/system.object.memberwiseclone?view=net-6.0

2022-03-31 07:34 UTC, PhilPJL commented on SolastaCommunityExpansion/Models/RacesContext.cs
> +        private static T MemberwiseClone<T>(T base_object)
Maybe Object.Instantiate would work as a deep copy.

2022-03-31 07:36 UTC, PhilPJL requested changes
Clone method is faulty

2022-03-31 12:16 UTC, ThyWoof commented on SolastaCommunityExpansion/Models/RacesContext.cs
> +        private static T MemberwiseClone<T>(T base_object)
this came from migration. Object.Instantiate won't work on this class. Any suggestions?

2022-03-31 12:26 UTC, PhilPJL commented on SolastaCommunityExpansion/Models/RacesContext.cs
> +        private static T MemberwiseClone<T>(T base_object)
Manually create a copy method.

var orig = CharacterRaceDefinitions.Halfling.RacePresentation;
var rp = new RacePresentation();

rp.SetMaleBeardShapeOptions(orig.MaleBeardShapeOptions);
... etc

2022-03-31 22:40 UTC, ThyWoof commented on SolastaCommunityExpansion/Models/RacesContext.cs
> +        private static T MemberwiseClone<T>(T base_object)
implemented https://github.com/Burtsev-Alexey/net-object-deep-copy

2022-04-01 07:55 UTC, PhilPJL approved these changes
Only issues I can think of are
1) the gnome and warlock images are high res and take up about 2Mb. The final .dll is <5Mb  total including the images.  Maybe they could be shrunk down.
2) was concerned the new .Copy could conflict with other .Copy methods but it doesn't seem to.  Maybe rename it DeepCopy?

2022-04-01 12:23 UTC, PhilPJL requested changes
I'm thinking Copy methods should be called DeepCopy to avoid accidentally using this Copy when there's a Copy extension method on a blueprint.

Also DeepCopy should throw if attempting to copy a UnityEngine.Object.  A DeepCopy of a blueprint/Unity object may cause problems and we should use Object.Instantiate etc in those cases.

2022-04-01 17:19 UTC, ThyWoof commented
renamed to DeepCopy and added check on unity objects

2022-04-01 18:33 UTC, PhilPJL approved these changes

2022-04-01 18:33 UTC, merged