Add rouge subclass opportunist
SolastaMods/SolastaCommunityExpansion pull request #1205
Opened 2022-04-25 16:58 UTC by dolenam317

### "Quick strike" when hero has higher initiative
![sneak_attack_due_to_higher_intiatiative](https://user-images.githubusercontent.com/19908936/165137244-e046dfab-b641-4914-aec3-054737709827.JPG)

### "Quick strike" when perform attack of opportunity
![disengate_and_sneak_attack_with_attack_of_opportunity](https://user-images.githubusercontent.com/19908936/165137190-7ad48156-2121-47fb-922e-aeb2ed50574e.JPG)

### "Debilitating strike" when sneak attack
![debilitating_strike](https://user-images.githubusercontent.com/19908936/165137270-5a6d1f0e-3b9b-4ff7-84a3-4bb6814156da.JPG)

2022-04-25 20:18 UTC, ThyWoof commented
The changes in Subclasses model don’t look right. I would expect only one line change there with the sub builder invocation. Please double check that. You might need to merge latest dev on your fork first.

2022-04-25 22:48 UTC, ThyWoof commented
Thanks for the contribution! Highlighted a few items on code but pretty solid.

2022-04-25 23:06 UTC, ThyWoof requested changes

2022-04-27 06:09 UTC, dolenam317 commented
Superseded by this [PR](https://github.com/SolastaMods/SolastaCommunityExpansion/pull/1206).

2022-04-27 06:09 UTC, closed without merging