Custom feature selection
SolastaMods/SolastaCommunityExpansion pull request #1218
Opened 2022-05-02 16:04 UTC by EnderWiggin

Adds CustomFeatureDefinitionSet and ReplaceCustomFeatureDefinitionSet that allow for feature selection and replacement on separate levelup stage similar to spell selection. As a bonus some warlock fixes.

2022-05-02 21:20 UTC, ThyWoof commented on SolastaCommunityExpansion/Patches/GameUi/CharacterPanel/CharacterEditorPatcher.cs
> +                var stagePanelPrefabs =
You can get this on Postfix arguments as you did with ___stagePanelsByName.

2022-05-02 21:22 UTC, ThyWoof commented on SolastaCommunityExpansion/Patches/GameUi/CharacterPanel/CharacterEditorPatcher.cs
> +                if (__instance is not CharacterLevelUpScreen)
If I remember correctly this method gets called 3 times: CharacterEditionScreen, CharacterCreationScreen and CharacterLevelUpScreen. Don't we only need this on LevelUpScreen?

2022-05-02 21:24 UTC, ThyWoof commented on SolastaCommunityExpansion/Patches/GameUi/CharacterPanel/CharacterEditorPatcher.cs
> +                var characterCreationScreen = Gui.GuiService.GetScreen<CharacterCreationScreen>();
this and __instance are the same depending on the call.

2022-05-02 21:25 UTC, ThyWoof commented on SolastaCommunityExpansion/Patches/GameUi/CharacterInspection/CharacterInspectionScreenPatcher.cs
> +    [HarmonyPatch(typeof(CharacterInspectionScreen), "Bind")]
I don't see any changes in MC leveraging this. I do this there already.

2022-05-02 21:28 UTC, ThyWoof commented on SolastaCommunityExpansion/Patches/GameUi/CharacterInspection/CharacterInformationPanelPatcher.cs
> +﻿using System.Collections.Generic;
is this original game code we copied over and added additional behavior? If so please mark the changes as we can always consider a transpiler later on.

2022-05-02 21:29 UTC, ThyWoof commented on SolastaCommunityExpansion/Patches/CustomFeatures/CustomSpells/CharacterBuildingManagerPatcher.cs
> +    internal static class CharacterBuildingManagePatcher
typo: CharacterBuildingManagerPatcher

2022-05-02 21:29 UTC, ThyWoof commented on SolastaMulticlass/Patches/LevelUp/CharacterEditionScreenPatcher.cs
> +using SolastaCommunityExpansion;
are these changes required?

2022-05-02 21:31 UTC, ThyWoof commented on SolastaCommunityExpansion/Patches/GameUi/CharacterPanel/CharacterEditorPatcher.cs
> +                    foreach (var e in ___stagePanelsByName)
we can loop here until Count -2 to avoid the IF inside the loop. Add the custom stage and Count-1 after the loop.

2022-05-02 21:34 UTC, ThyWoof commented on SolastaCommunityExpansion/Patches/Bugfix/LocalCommandManagerPatcher.cs
> +            ServiceRepository.GetService<ICharacterBuildingService>().UnassignLastSubclass(hero, onlyIfCurrentLevel);
We need to add a hidden setting like other bug fixes to easily allow disabling it if required. Check pattern on others pls.

2022-05-02 21:37 UTC, ThyWoof requested changes
please check inline comments.

2022-05-03 11:55 UTC, EnderWiggin commented on SolastaCommunityExpansion/Patches/GameUi/CharacterPanel/CharacterEditorPatcher.cs
> +                if (__instance is not CharacterLevelUpScreen)
If some custom feature is on level 1 of a class, we'll need it on chaacter creation.

2022-05-03 11:57 UTC, EnderWiggin commented on SolastaCommunityExpansion/Patches/GameUi/CharacterPanel/CharacterEditorPatcher.cs
> +                    foreach (var e in ___stagePanelsByName)
why if inside the loop is bad?

2022-05-03 12:01 UTC, EnderWiggin commented on SolastaCommunityExpansion/Patches/GameUi/CharacterPanel/CharacterEditorPatcher.cs
> +                var characterCreationScreen = Gui.GuiService.GetScreen<CharacterCreationScreen>();
No, I specifically take creation screen since I know where SpellSelection panel prefab in its panel prefabs. In theory we might look through current screen's prefabs in search of spell selection, not sure it will be better.

2022-05-03 12:02 UTC, EnderWiggin commented on SolastaCommunityExpansion/Patches/GameUi/CharacterPanel/CharacterEditorPatcher.cs
> +                var stagePanelPrefabs =
Same as above comment - I specifically take prefabs out of CharacterCreationScreen

2022-05-04 00:05 UTC, ThyWoof approved these changes

2022-05-05 01:48 UTC, ThyWoof approved these changes

2022-05-05 01:49 UTC, merged